/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package snake.and.ladder;

import java.util.Scanner;
import snake.and.ladder.model.Game;
import snake.and.ladder.model.Player;

public class App {

  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    Scanner scanner = new Scanner(System.in);
    System.out.println("Enter board Size");
    int boardSize = scanner.nextInt();
    System.out.println("Enter number of players");
    int numberOfPlayers = scanner.nextInt();
    System.out.println("Enter number of snakes");
    int numSnakes = scanner.nextInt();
    System.out.println("Enter number of ladders");
    int numLadders = scanner.nextInt();

    Game game = new Game(numLadders, numSnakes, boardSize);
    for (int i = 0; i < numberOfPlayers; i++) {
      System.out.println("Enter player name");
      String pName = scanner.next();
      Player player = new Player(pName);
      game.addPlayer(player);
    }
    game.playGame();
  }
}
